<?php
/**
 * SwiftOtter_Base is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SwiftOtter_Base is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with SwiftOtter_Base. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright: 2013 (c) SwiftOtter Studios
 *
 * @author Tyler Schade
 * @copyright Swift Otter Studios, 10/5/16
 * @package default
 **/
?>

<?php
/**
 * @var \TylerSchade\Contacts\Block\View $block
 */
?>
<?php if ($block->getIsLoggedIn()): ?>
<ol class="contact-list">
    <?php /** @var TylerSchade\Contacts\Model\Contact $contact */ ?>
    <?php foreach ($block->getCollection() as $contact): ?>
    <li class="contact">
        <a href="<?php echo $contact->getUrl(); ?>" class="contact-name">
            <?php echo $contact->getData('first_name'); ?>
            <?php echo $contact->getData('last_name'); ?>
            - <?php echo $contact->getData('email_address'); ?>
        </a>

    </li>
    <?php endforeach; ?>
</ol>
<?php else: ?>
    <?php echo $block->getChildHtml('unauthorized'); ?>
<?php endif; ?>
